; === GENERATED by tools/gen_tritone_module.py --name lowlands from 'assets/music/lowlands.asm' ===
                SECTION code_user
                PUBLIC  _lowlands_play
                EXTERN  TRI_PLAY
                EXTERN  _tritone_ticks

_lowlands_play:
                PUSH  IX            ; preserve sdcc frame pointer
                LD    HL,0
                LD    (_tritone_ticks),HL   ; reset shared entropy
                LD    HL,MUSICDATA
                CALL  TRI_PLAY
                POP   IX
                RET

MUSICDATA:

; *** Song layout (generated by tools/txt2tritone.py) ***
LOOPSTART:            DEFW      PAT0
                      DEFW      PAT1
                      DEFW      PAT2
                      DEFW      PAT3
                      DEFW      PAT4
                      DEFW      PAT5
                      DEFW      PAT6
                      DEFW      $0000
                      DEFW      LOOPSTART

; *** Patterns ***
PAT0:
                DEFW  6852     ; Pattern tempo (speed 15)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $85,$D8,$83,$7A,$81,$76
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $84,$61,$83,$7A,$82,$30
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT1:
                DEFW  6852     ; Pattern tempo (speed 15)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $85,$D8,$83,$7A,$81,$76
                DEFB  $86,$8F,$01,$01
                DEFB  $86,$F3,$84,$61,$01
                DEFB  $86,$8F,$01,$01
                DEFB  $85,$D8,$83,$7A,$82,$30
                DEFB  $01,$01,$01
                DEFB  $85,$35,$84,$61,$01
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT2:
                DEFW  6852     ; Pattern tempo (speed 15)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$61,$83,$48,$82,$30
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$81,$A4
                DEFB  $01,$01,$01
                DEFB  $83,$E6,$83,$48,$01
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT3:
                DEFW  6852     ; Pattern tempo (speed 15)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $85,$35,$83,$E6,$82,$9A
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $85,$D8,$84,$61,$01
                DEFB  $86,$8F,$85,$35,$81,$F3
                DEFB  $01,$01,$01
                DEFB  $85,$35,$83,$E6,$01
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT4:
                DEFW  6852     ; Pattern tempo (speed 15)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $85,$D8,$84,$EA,$81,$F3
                DEFB  $01,$01,$01
                DEFB  $85,$35,$84,$61,$01
                DEFB  $01,$01,$01
                DEFB  $83,$E6,$83,$48,$81,$76
                DEFB  $01,$01,$01
                DEFB  $85,$35,$83,$48,$01
                DEFB  $84,$EA,$82,$EC,$01
                DEFB  $FF  ; End of Pattern

PAT5:
                DEFW  6852     ; Pattern tempo (speed 15)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$61,$83,$7A,$81,$76
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $83,$E6,$83,$48,$82,$30
                DEFB  $01,$01,$01
                DEFB  $83,$7A,$82,$EC,$01
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT6:
                DEFW  6852     ; Pattern tempo (speed 15)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $82,$EC,$83,$7A,$81,$76
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern
