; === GENERATED by tools/gen_tritone_module.py --name oro from 'assets/music/oro se do bheatha.asm' ===
                SECTION code_user
                PUBLIC  _oro_play
                EXTERN  TRI_PLAY
                EXTERN  _tritone_ticks

_oro_play:
                PUSH  IX            ; preserve sdcc frame pointer
                LD    HL,0
                LD    (_tritone_ticks),HL   ; reset shared entropy
                LD    HL,MUSICDATA
                CALL  TRI_PLAY
                POP   IX
                RET

MUSICDATA:

; *** Song layout ***
LOOPSTART:            DEFW      PAT0
                      DEFW      PAT1
                      DEFW      PAT2
                      DEFW      PAT3
                      DEFW      PAT4
                      DEFW      PAT5
                      DEFW      PAT6
                      DEFW      PAT7
                      DEFW      PAT8
                      DEFW      $0000
                      DEFW      LOOPSTART

; *** Patterns ***
PAT0:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $0A,$F4,$EA,$83,$E8,$82,$31
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $0A,$F4,$E7,$83,$E8,$82,$31
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $F4,$63,$83,$7B,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $F4,$E7,$83,$E8,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $FF  ; End of Pattern

PAT1:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $85,$35,$84,$63,$82,$31
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$E7,$83,$E8,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$63,$83,$7B,$82,$31
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $83,$7B,$82,$ED,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $FF  ; End of Pattern

PAT2:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $84,$63,$83,$7B,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$63,$83,$7B,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$63,$83,$7B,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$E7,$83,$E8,$01
                DEFB  $FF  ; End of Pattern

PAT3:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $84,$63,$82,$ED,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $83,$49,$82,$76,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $83,$7B,$82,$ED,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$63,$83,$7B,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $FF  ; End of Pattern

PAT4:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $84,$E7,$83,$E8,$82,$31
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$E7,$83,$E8,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$E7,$83,$E8,$82,$31
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$63,$83,$7B,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$E7,$83,$E8,$01
                DEFB  $FF  ; End of Pattern

PAT5:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $85,$35,$84,$63,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $84,$E7,$83,$E8,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $85,$35,$84,$63,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $86,$92,$85,$35,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $FF  ; End of Pattern

PAT6:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $86,$92,$83,$E8,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$82,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$81,$A4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $86,$92,$83,$E8,$82,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $FF  ; End of Pattern

PAT7:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $86,$F6,$85,$DB,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $85,$35,$84,$63,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $86,$92,$85,$35,$81,$F4
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $85,$35,$84,$63,$81,$76
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $FF  ; End of Pattern

PAT8:
                DEFW  2284     ; Pattern tempo (5 frames/row, ~140 BPM)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB      $84,$E7,$83,$E8,$82,$31
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $85,$35,$84,$63,$01
                DEFB      $84,$E7,$83,$E8,$00
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB      $01    ,$01    ,$01
                DEFB  $FF  ; End of Pattern
