; === GENERATED by tools/gen_tritone_module.py --name spanish from 'assets/music/spanish.asm' ===
                SECTION code_user
                PUBLIC  _spanish_play
                EXTERN  TRI_PLAY
                EXTERN  _tritone_ticks

_spanish_play:
                PUSH  IX            ; preserve sdcc frame pointer
                LD    HL,0
                LD    (_tritone_ticks),HL   ; reset shared entropy
                LD    HL,MUSICDATA
                CALL  TRI_PLAY
                POP   IX
                RET

MUSICDATA:

; *** Song layout (generated by tools/txt2tritone.py) ***
LOOPSTART:            DEFW      PAT0
                      DEFW      PAT1
                      DEFW      PAT2
                      DEFW      PAT3
                      DEFW      PAT4
                      DEFW      PAT5
                      DEFW      PAT6
                      DEFW      PAT7
                      DEFW      PAT8
                      DEFW      PAT9
                      DEFW      PAT10
                      DEFW      PAT11
                      DEFW      PAT12
                      DEFW      PAT13
                      DEFW      PAT14
                      DEFW      PAT15
                      DEFW      $0000
                      DEFW      LOOPSTART

; *** Patterns ***
PAT0:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$81,$D7
                DEFB  $01,$01,$01
                DEFB  $83,$AE,$82,$EC,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $84,$22,$83,$48,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT1:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$81,$D7
                DEFB  $01,$01,$01
                DEFB  $01,$01,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $83,$AE,$82,$EC,$82,$C2
                DEFB  $84,$22,$83,$48,$01
                DEFB  $FF  ; End of Pattern

PAT2:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$61,$83,$AE,$81,$76
                DEFB  $01,$01,$01
                DEFB  $84,$22,$83,$48,$82,$30
                DEFB  $01,$01,$01
                DEFB  $83,$AE,$82,$EC,$82,$30
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT3:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$81,$A4
                DEFB  $83,$48,$82,$C2,$01
                DEFB  $82,$C2,$82,$30,$82,$75
                DEFB  $01,$01,$01
                DEFB  $82,$C2,$82,$30,$82,$75
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT4:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$81,$D7
                DEFB  $01,$01,$01
                DEFB  $83,$AE,$82,$EC,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $84,$22,$83,$48,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT5:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$82,$75
                DEFB  $01,$01,$01
                DEFB  $01,$01,$81,$D7
                DEFB  $01,$01,$01
                DEFB  $84,$22,$83,$48,$81,$D7
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT6:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$61,$83,$AE,$81,$A4
                DEFB  $01,$01,$01
                DEFB  $84,$EA,$84,$22,$82,$75
                DEFB  $01,$01,$01
                DEFB  $84,$61,$83,$AE,$82,$75
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT7:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$22,$83,$48,$81,$A4
                DEFB  $01,$01,$01
                DEFB  $01,$01,$82,$75
                DEFB  $01,$01,$01
                DEFB  $84,$22,$83,$48,$82,$75
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT8:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$61,$83,$AE,$82,$30
                DEFB  $01,$01,$01
                DEFB  $84,$22,$83,$48,$81,$A4
                DEFB  $01,$01,$01
                DEFB  $84,$61,$83,$AE,$81,$A4
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT9:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$EA,$84,$22,$82,$75
                DEFB  $01,$01,$01
                DEFB  $84,$61,$83,$AE,$81,$D7
                DEFB  $01,$01,$01
                DEFB  $84,$EA,$84,$22,$81,$D7
                DEFB  $84,$EA,$84,$22,$01
                DEFB  $FF  ; End of Pattern

PAT10:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $85,$84,$84,$61,$81,$D7
                DEFB  $84,$EA,$84,$22,$01
                DEFB  $84,$61,$83,$AE,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $83,$AE,$82,$EC,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT11:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$81,$D7
                DEFB  $83,$48,$82,$C2,$01
                DEFB  $82,$C2,$82,$30,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $85,$84,$84,$61,$82,$C2
                DEFB  $84,$EA,$84,$22,$01
                DEFB  $FF  ; End of Pattern

PAT12:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $84,$61,$83,$AE,$81,$76
                DEFB  $01,$01,$01
                DEFB  $83,$AE,$82,$EC,$82,$30
                DEFB  $01,$01,$01
                DEFB  $83,$AE,$82,$EC,$82,$30
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT13:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$81,$A4
                DEFB  $83,$48,$82,$C2,$01
                DEFB  $82,$C2,$82,$30,$82,$75
                DEFB  $01,$01,$01
                DEFB  $82,$75,$82,$11,$82,$75
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT14:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $82,$C2,$82,$30,$82,$C2
                DEFB  $01,$01,$01
                DEFB  $84,$61,$83,$48,$82,$11
                DEFB  $01,$01,$01
                DEFB  $84,$22,$83,$48,$82,$11
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern

PAT15:
                DEFW  11420     ; Pattern tempo (speed 25)
                ;    Drum,Chan.1 ,Chan.2 ,Chan.3
                DEFB  $83,$AE,$82,$EC,$81,$D7
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $01,$01,$01
                DEFB  $82,$C2,$82,$30,$01
                DEFB  $01,$01,$01
                DEFB  $FF  ; End of Pattern
