#ifndef _SPRITES_PACKED_H_
#define _SPRITES_PACKED_H_

#include <stdint.h>

/* GENERATED by tools/pack_sprites.py — all sprite pixels live in a
 * ZX0 blob (977 B) decompressed at boot into a low-RAM arena
 * ($6A00..$78E8, 3816 B), freeing uncontended RAM. */

#define DIVER_WIDTH 16
#define DIVER_HEIGHT 16
#define DIVER_FRAMES 4
#define RAY_WIDTH 32
#define RAY_HEIGHT 32
#define RAY_FRAMES 2
#define SHARK_WIDTH 32
#define SHARK_HEIGHT 32
#define SHARK_FRAMES 2
#define STATUE_WIDTH 32
#define STATUE_HEIGHT 32
#define STATUE_FRAMES 2
#define TABLET_WIDTH 32
#define TABLET_HEIGHT 32
#define TABLET_FRAMES 2
#define ALTAR_WIDTH 32
#define ALTAR_HEIGHT 32
#define ALTAR_FRAMES 2
#define FIRSTAID_WIDTH 32
#define FIRSTAID_HEIGHT 32
#define FIRSTAID_FRAMES 2
#define OXYGEN_TANK_WIDTH 32
#define OXYGEN_TANK_HEIGHT 32
#define OXYGEN_TANK_FRAMES 2
#define MAP_ITEM_WIDTH 32
#define MAP_ITEM_HEIGHT 32
#define MAP_ITEM_FRAMES 2
#define LOG_ITEM_WIDTH 32
#define LOG_ITEM_HEIGHT 32
#define LOG_ITEM_FRAMES 2
#define BOAT_WIDTH 48
#define BOAT_HEIGHT 32
#define BOAT_FRAMES 1
#define MINIMAP_GRID_WIDTH 32
#define MINIMAP_GRID_HEIGHT 16
#define MINIMAP_GRID_FRAMES 2

#define SPRITE_ARENA 0x6A00u
extern const unsigned char sprites_zx0[];
void sprites_unpack(void);   /* decompress blob -> arena (call once at boot) */

#define diver_f1 ((const uint8_t *)(SPRITE_ARENA + 0))
#define diver_f2 ((const uint8_t *)(SPRITE_ARENA + 32))
#define diver_f3 ((const uint8_t *)(SPRITE_ARENA + 64))
#define diver_f4 ((const uint8_t *)(SPRITE_ARENA + 96))
#define diver_attr ((const uint8_t *)(SPRITE_ARENA + 128))
#define ray_f1 ((const uint8_t *)(SPRITE_ARENA + 144))
#define ray_f1_16 ((const uint8_t *)(SPRITE_ARENA + 272))
#define ray_f1_8 ((const uint8_t *)(SPRITE_ARENA + 304))
#define ray_f2 ((const uint8_t *)(SPRITE_ARENA + 312))
#define ray_f2_16 ((const uint8_t *)(SPRITE_ARENA + 440))
#define ray_f2_8 ((const uint8_t *)(SPRITE_ARENA + 472))
#define ray_attr ((const uint8_t *)(SPRITE_ARENA + 480))
#define shark_f1 ((const uint8_t *)(SPRITE_ARENA + 512))
#define shark_f1_16 ((const uint8_t *)(SPRITE_ARENA + 640))
#define shark_f1_8 ((const uint8_t *)(SPRITE_ARENA + 672))
#define shark_f2 ((const uint8_t *)(SPRITE_ARENA + 680))
#define shark_f2_16 ((const uint8_t *)(SPRITE_ARENA + 808))
#define shark_f2_8 ((const uint8_t *)(SPRITE_ARENA + 840))
#define shark_attr ((const uint8_t *)(SPRITE_ARENA + 848))
#define statue_f1 ((const uint8_t *)(SPRITE_ARENA + 880))
#define statue_f1_16 ((const uint8_t *)(SPRITE_ARENA + 1008))
#define statue_f1_8 ((const uint8_t *)(SPRITE_ARENA + 1040))
#define statue_f2 ((const uint8_t *)(SPRITE_ARENA + 1048))
#define statue_f2_16 ((const uint8_t *)(SPRITE_ARENA + 1176))
#define statue_f2_8 ((const uint8_t *)(SPRITE_ARENA + 1208))
#define statue_attr ((const uint8_t *)(SPRITE_ARENA + 1216))
#define tablet_f1 ((const uint8_t *)(SPRITE_ARENA + 1248))
#define tablet_f1_16 ((const uint8_t *)(SPRITE_ARENA + 1376))
#define tablet_f1_8 ((const uint8_t *)(SPRITE_ARENA + 1408))
#define tablet_f2 ((const uint8_t *)(SPRITE_ARENA + 1416))
#define tablet_f2_16 ((const uint8_t *)(SPRITE_ARENA + 1544))
#define tablet_f2_8 ((const uint8_t *)(SPRITE_ARENA + 1576))
#define tablet_attr ((const uint8_t *)(SPRITE_ARENA + 1584))
#define altar_f1 ((const uint8_t *)(SPRITE_ARENA + 1616))
#define altar_f1_16 ((const uint8_t *)(SPRITE_ARENA + 1744))
#define altar_f1_8 ((const uint8_t *)(SPRITE_ARENA + 1776))
#define altar_f2 ((const uint8_t *)(SPRITE_ARENA + 1784))
#define altar_f2_16 ((const uint8_t *)(SPRITE_ARENA + 1912))
#define altar_f2_8 ((const uint8_t *)(SPRITE_ARENA + 1944))
#define altar_attr ((const uint8_t *)(SPRITE_ARENA + 1952))
#define firstaid_f1 ((const uint8_t *)(SPRITE_ARENA + 1984))
#define firstaid_f1_16 ((const uint8_t *)(SPRITE_ARENA + 2112))
#define firstaid_f1_8 ((const uint8_t *)(SPRITE_ARENA + 2144))
#define firstaid_f2 ((const uint8_t *)(SPRITE_ARENA + 2152))
#define firstaid_f2_16 ((const uint8_t *)(SPRITE_ARENA + 2280))
#define firstaid_f2_8 ((const uint8_t *)(SPRITE_ARENA + 2312))
#define firstaid_attr ((const uint8_t *)(SPRITE_ARENA + 2320))
#define oxygen_tank_f1 ((const uint8_t *)(SPRITE_ARENA + 2352))
#define oxygen_tank_f1_16 ((const uint8_t *)(SPRITE_ARENA + 2480))
#define oxygen_tank_f1_8 ((const uint8_t *)(SPRITE_ARENA + 2512))
#define oxygen_tank_f2 ((const uint8_t *)(SPRITE_ARENA + 2520))
#define oxygen_tank_f2_16 ((const uint8_t *)(SPRITE_ARENA + 2648))
#define oxygen_tank_f2_8 ((const uint8_t *)(SPRITE_ARENA + 2680))
#define oxygen_tank_attr ((const uint8_t *)(SPRITE_ARENA + 2688))
#define map_item_f1 ((const uint8_t *)(SPRITE_ARENA + 2720))
#define map_item_f1_16 ((const uint8_t *)(SPRITE_ARENA + 2848))
#define map_item_f1_8 ((const uint8_t *)(SPRITE_ARENA + 2880))
#define map_item_f2 ((const uint8_t *)(SPRITE_ARENA + 2888))
#define map_item_f2_16 ((const uint8_t *)(SPRITE_ARENA + 3016))
#define map_item_f2_8 ((const uint8_t *)(SPRITE_ARENA + 3048))
#define map_item_attr ((const uint8_t *)(SPRITE_ARENA + 3056))
#define log_item_f1 ((const uint8_t *)(SPRITE_ARENA + 3088))
#define log_item_f1_16 ((const uint8_t *)(SPRITE_ARENA + 3216))
#define log_item_f1_8 ((const uint8_t *)(SPRITE_ARENA + 3248))
#define log_item_f2 ((const uint8_t *)(SPRITE_ARENA + 3256))
#define log_item_f2_16 ((const uint8_t *)(SPRITE_ARENA + 3384))
#define log_item_f2_8 ((const uint8_t *)(SPRITE_ARENA + 3416))
#define log_item_attr ((const uint8_t *)(SPRITE_ARENA + 3424))
#define boat_bitmap ((const uint8_t *)(SPRITE_ARENA + 3456))
#define boat_attr ((const uint8_t *)(SPRITE_ARENA + 3648))
#define minimap_grid_f1 ((const uint8_t *)(SPRITE_ARENA + 3672))
#define minimap_grid_f2 ((const uint8_t *)(SPRITE_ARENA + 3736))
#define minimap_grid_attr ((const uint8_t *)(SPRITE_ARENA + 3800))

#endif /* _SPRITES_PACKED_H_ */
