#!/usr/bin/env python3
"""Split a standalone Beepola Tritone .asm into z88dk-linkable modules that
SHARE one copy of the engine, instead of embedding the ~300-line player in
every tune.

Two output modes:

  --engine   Emit the shared engine module (once for the whole game):
             PUBLIC TRI_PLAY (HL = song order-table pointer) and PUBLIC
             _tritone_ticks (rows played, PRNG entropy).  This is the player
             code + DRUM_SETTINGS only — no song data.

  --name N   Emit a per-tune module: a tiny C-callable wrapper
                 void N_play(void)  ->  _N_play
             that resets _tritone_ticks and CALLs the EXTERN TRI_PLAY with
             this tune's data, followed by the song data (order table +
             patterns) only.  No engine.

Engine transforms vs the Beepola export:
  * drop ORG (linker places the section) and the standalone entry stub;
  * drop the exit EI (this project keeps interrupts disabled forever);
  * inject the per-row _tritone_ticks increment in the NEXT_ROW transition.

N_play() BLOCKS, looping the tune on all three beeper channels, and returns as
soon as any key/joystick is pressed (Tritone's built-in check).

Usage:
  tools/gen_tritone_module.py TEMPLATE.asm --engine -o tritone_engine.asm
  tools/gen_tritone_module.py TUNE.asm     --name NAME -o NAME_linkable.asm
"""
import argparse
import os
import re


def split_at_musicdata(lines):
    """Return (engine_lines, data_lines) where data starts at 'MUSICDATA:'."""
    idx = next(i for i, l in enumerate(lines) if l.strip().startswith('MUSICDATA:'))
    return lines[:idx], lines[idx:]


def build_engine(src_text, src_path):
    engine_src, _ = split_at_musicdata(src_text.split("\n"))
    out = [
        f"; === GENERATED by tools/gen_tritone_module.py --engine from '{src_path}' ===",
        "; Shared Shiru Tritone v2 player.  One copy links into the whole game;",
        "; each tune is a separate data module that CALLs TRI_PLAY.",
        "                SECTION code_user",
        "                PUBLIC  TRI_PLAY",
        "                PUBLIC  _tritone_ticks",
        "",
    ]
    def norm(x):
        return re.sub(r'\s+', ' ', x.split(';')[0].strip())

    i = 0
    while i < len(engine_src):
        l = engine_src[i]
        s = l.strip()

        if s.upper().startswith("ORG"):                       # linker places it
            i += 1
            continue

        # --- click reduction: replace the row-end block (unconditional
        #     "XOR A / OUT ($FE),A" reset + key check + "JP Z,NEXT_ROW") with a
        #     version that, when the NEXT row is a pure sustain ($01,$01,$01,
        #     no drum/note/end), keeps the speaker toggling and replays the
        #     same channels for another row instead of zeroing the speaker and
        #     re-reading/re-setting-up. The XOR-A/OUT reset now happens ONLY on
        #     real note-change rows, so held notes no longer click each row. ---
        if norm(l) == "XOR A" and i + 1 < len(engine_src) \
                and norm(engine_src[i + 1]) == "OUT ($FE),A":
            j = i
            while "Z,NEXT_ROW" not in engine_src[j].replace(" ", ""):
                j += 1
            out += [
                "                LD    (PREV_HL + 1),HL      ; save CH0 phase",
                "",
                "                IN    A,($1F)               ; --- key check (every row) ---",
                "                AND   $1F",
                "                LD    C,A",
                "                XOR   A",
                "                IN    A,($FE)",
                "                CPL",
                "CHECK_KEMPSTON: OR    C            ; set to NOP if no kempston i/f",
                "                AND   $1F",
                "                JP    NZ,STOP_PLAYER        ; key/joystick pressed -> stop",
                "",
                "                LD    HL,(NEXT_ROW_POS+1)   ; peek next row for pure sustain",
                "                LD    A,(HL)",
                "                CP    1",
                "                JR    NZ,ROW_CHANGE",
                "                INC   HL",
                "                LD    A,(HL)",
                "                CP    1",
                "                JR    NZ,ROW_CHANGE",
                "                INC   HL",
                "                LD    A,(HL)",
                "                CP    1",
                "                JR    NZ,ROW_CHANGE",
                "                INC   HL",
                "                LD    (NEXT_ROW_POS+1),HL   ; consume 3 sustain bytes",
                "                LD    BC,(CNT0+1)           ; restore CH0 incr (C clobbered)",
                "                LD    DE,(TEMPO+1)          ; reload row-duration counter",
                "                LD    HL,(PREV_HL+1)        ; restore CH0 phase",
                "                JP    SOUND_LOOP            ; continue tone, no reset/click",
                "ROW_CHANGE:",
                "                XOR   A",
                "                OUT   ($FE),A               ; reset speaker only on real changes",
                "                JP    NEXT_ROW",
            ]
            i = j + 1
            continue
        if s.replace(" ", "").upper() == "LDHL,MUSICDATA":     # drop standalone stub
            assert "TRI_PLAY" in engine_src[i + 1] and engine_src[i + 2].strip().upper() == "RET"
            i += 3
            continue
        if s.upper() == "EI":                                  # keep interrupts off
            i += 1
            continue
        if s == "NEXT_ROW:":                                   # per-row entropy tick
            # HL is dead here (NEXT_ROW_POS reloads it on the next line), so we
            # clobber it freely.  We must NOT touch the stack: Tritone reuses SP
            # as the CH2 phase accumulator across the row loop, so SP is not a
            # valid stack pointer at NEXT_ROW.
            out.append(l)
            out += [
                "                LD    HL,(_tritone_ticks)   ; --- row-count entropy ---",
                "                INC   HL",
                "                LD    (_tritone_ticks),HL",
            ]
            i += 1
            continue
        out.append(l)
        i += 1

    out += ["", "_tritone_ticks: DEFW  0    ; rows played (shared PRNG entropy)"]
    return "\n".join(out) + "\n"


def build_data_module(src_text, name, src_path):
    _, data = split_at_musicdata(src_text.split("\n"))
    out = [
        f"; === GENERATED by tools/gen_tritone_module.py --name {name} from '{src_path}' ===",
        "                SECTION code_user",
        f"                PUBLIC  _{name}_play",
        "                EXTERN  TRI_PLAY",
        "                EXTERN  _tritone_ticks",
        "",
        f"_{name}_play:",
        "                PUSH  IX            ; preserve sdcc frame pointer",
        "                LD    HL,0",
        "                LD    (_tritone_ticks),HL   ; reset shared entropy",
        "                LD    HL,MUSICDATA",
        "                CALL  TRI_PLAY",
        "                POP   IX",
        "                RET",
        "",
    ]
    out += data
    return "\n".join(out).rstrip("\n") + "\n"


def main():
    ap = argparse.ArgumentParser(description="Tritone .asm -> shared engine + data modules")
    ap.add_argument("input", help="standalone Tritone .asm (engine + data)")
    ap.add_argument("-o", "--output", required=True, help="output .asm")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--engine", action="store_true",
                   help="emit the shared engine module (TRI_PLAY, _tritone_ticks)")
    g.add_argument("--name", default=None,
                   help="emit a per-tune data module exposing _NAME_play")
    args = ap.parse_args()

    src = open(args.input).read()
    if args.engine:
        open(args.output, "w").write(build_engine(src, args.input))
        print(f"wrote {args.output}  (shared engine: TRI_PLAY, _tritone_ticks)")
    else:
        name = re.sub(r'\W', '_', args.name.lower()).strip('_')
        open(args.output, "w").write(build_data_module(src, name, args.input))
        print(f"wrote {args.output}  (tune module: _{name}_play)")


if __name__ == "__main__":
    main()
