#!/usr/bin/env python3
"""Generate a z88dk-linkable, C-callable version of the Beepola Tritone player.

Input : assets/music/oro se do bheatha.asm  (canonical Beepola export, standalone)
Output: a linkable module exposing  void oro_play(void)  ->  asm symbol _oro_play

Transforms applied (the export is otherwise byte-identical):
  1. Drop `ORG 40000`             — the linker places the section.
  2. Add SECTION + PUBLIC _oro_play and wrap the entry so IX (sdcc frame
     pointer) is preserved across the call.
  3. Remove the `EI` on exit      — this project keeps interrupts disabled
     forever (startup=31, IM 1, never re-enabled); the player DIs on entry
     and we must leave them disabled on return.

oro_play() blocks, looping the shanty on all three beeper channels, and
returns as soon as any key/joystick is pressed (Tritone's built-in check).

  4. Inject a 16-bit row counter `_oro_ticks` (PUBLIC) incremented once per
     row.  It is zeroed on entry and reflects how many rows played before the
     user pressed a key — human reaction time = PRNG entropy for the caller.
     The increment lives in the row-transition code, well outside the tight
     sound loop, so tempo is unaffected.
"""
import sys

SRC = "assets/music/oro se do bheatha.asm"
OUT = sys.argv[1] if len(sys.argv) > 1 else "assets/music/oro_linkable.asm"

lines = open(SRC).read().split("\n")
out = []
out.append("; === GENERATED by tools/gen_oro_asm.py from '%s' — do not edit ===" % SRC)
out.append("                SECTION code_user")
out.append("                PUBLIC  _oro_play")
out.append("                PUBLIC  _oro_ticks")
out.append("")

i = 0
while i < len(lines):
    l = lines[i]
    s = l.strip()

    # 1. drop the standalone ORG
    if s.startswith("ORG"):
        i += 1
        continue

    # 2. replace the standalone entry (LD HL,MUSICDATA / CALL TRI_PLAY / RET)
    #    with a C-callable, IX-preserving wrapper.
    if s.replace(" ", "").upper() == "LDHL,MUSICDATA":
        assert "TRI_PLAY" in lines[i + 1] and lines[i + 2].strip().upper() == "RET"
        out += [
            "_oro_play:",
            "                PUSH  IX            ; preserve sdcc frame pointer",
            "                LD    HL,0",
            "                LD    (_oro_ticks),HL   ; reset row-count entropy",
            "                LD    HL,MUSICDATA",
            "                CALL  TRI_PLAY",
            "                POP   IX",
            "                RET",
            "_oro_ticks:     DEFW  0             ; rows played (PRNG entropy)",
        ]
        i += 3
        continue

    # 4. inject the per-row tick counter right after the NEXT_ROW label
    if s == "NEXT_ROW:":
        out.append(l)
        out += [
            "                PUSH  HL            ; --- injected row-count entropy ---",
            "                LD    HL,(_oro_ticks)",
            "                INC   HL",
            "                LD    (_oro_ticks),HL",
            "                POP   HL",
        ]
        i += 1
        continue

    # 3. drop the lone EI on the player's exit path (keep interrupts disabled)
    if s.upper() == "EI":
        i += 1
        continue

    out.append(l)
    i += 1

open(OUT, "w").write("\n".join(out))
print("wrote", OUT, "(%d lines)" % len(out))
