#!/usr/bin/env python3
"""pack_sprites.py — Pack all sprite arrays into one ZX0 blob + arena macros.

Reads the per-sprite headers generated by zxp2header.py, concatenates every
`const uint8_t NAME[N] = {...}` array into a single blob, ZX0-compresses it,
and emits two headers:

  include/sprites_packed.h  dimension #defines, SPRITE_ARENA base, an
                            `extern` for the blob, `#define NAME (arena+off)`
                            for every sprite, and sprites_unpack() decl.
  include/sprites_blob.h    the compressed blob array (included once, by
                            sprites.c).

At runtime sprites_unpack() decompresses the blob into the low-RAM arena, so
the ~3.8 KB of resident sprite pixels no longer occupy uncontended RAM.

Usage: pack_sprites.py --arena 0x6A00 --zx0 /path/to/zx0 --outdir include
"""
import argparse
import os
import re
import subprocess

# Fixed order — offsets follow this; must stay stable.
SPRITES = ["diver", "ray", "shark", "statue", "tablet", "altar", "firstaid",
           "oxygen_tank", "map_item", "log_item", "boat", "minimap_grid"]

ARR_RE = re.compile(r'const\s+uint8_t\s+(\w+)\s*\[\s*\d*\s*\]\s*=\s*\{(.*?)\};', re.S)
DEF_RE = re.compile(r'#define\s+(\w+_(?:WIDTH|HEIGHT|FRAMES))\s+(\d+)')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arena", default="0x6A00")
    ap.add_argument("--zx0", default=os.environ.get("ZX0", "/tmp/ZX0/src/zx0"))
    ap.add_argument("--incdir", default="include")
    args = ap.parse_args()
    arena = int(args.arena, 16) if args.arena.startswith("0x") else int(args.arena)

    arrays = []          # (name, nbytes)
    defines = []         # (name, value)
    blob = bytearray()
    for s in SPRITES:
        txt = open(f"{args.incdir}/{s}.h").read()
        for name, val in DEF_RE.findall(txt):
            defines.append((name, val))
        for m in ARR_RE.finditer(txt):
            name = m.group(1)
            data = [int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{2})', m.group(2))]
            arrays.append((name, len(data), len(blob)))
            blob += bytes(data)

    total = len(blob)
    binp, zxp = "/tmp/sprites_pack.bin", "/tmp/sprites_pack.zx0"
    open(binp, "wb").write(blob)
    if os.path.exists(zxp):
        os.remove(zxp)
    subprocess.run([args.zx0, "-f", binp, zxp], check=True)
    comp = open(zxp, "rb").read()

    # sprites_packed.h — macros + dims + extern + unpack decl (all consumers)
    h = ["#ifndef _SPRITES_PACKED_H_", "#define _SPRITES_PACKED_H_", "",
         "#include <stdint.h>", "",
         "/* GENERATED by tools/pack_sprites.py — all sprite pixels live in a",
         f" * ZX0 blob ({len(comp)} B) decompressed at boot into a low-RAM arena",
         f" * (${arena:04X}..${arena+total:04X}, {total} B), freeing uncontended RAM. */", ""]
    for name, val in defines:
        h.append(f"#define {name} {val}")
    h += ["", f"#define SPRITE_ARENA 0x{arena:04X}u",
          "extern const unsigned char sprites_zx0[];",
          "void sprites_unpack(void);   /* decompress blob -> arena (call once at boot) */",
          ""]
    for name, n, off in arrays:
        h.append(f"#define {name} ((const uint8_t *)(SPRITE_ARENA + {off}))")
    h += ["", "#endif /* _SPRITES_PACKED_H_ */", ""]
    open(f"{args.incdir}/sprites_packed.h", "w").write("\n".join(h))

    # sprites_blob.h — the compressed data (included once, by sprites.c)
    b = ["#ifndef _SPRITES_BLOB_H_", "#define _SPRITES_BLOB_H_", "",
         f"/* GENERATED by tools/pack_sprites.py: {total} B -> {len(comp)} B ZX0 */",
         "const unsigned char sprites_zx0[] = {"]
    for i in range(0, len(comp), 16):
        b.append("    " + ", ".join(f"0x{x:02X}" for x in comp[i:i + 16]) + ",")
    b += ["};", "", "#endif /* _SPRITES_BLOB_H_ */", ""]
    open(f"{args.incdir}/sprites_blob.h", "w").write("\n".join(b))

    print(f"packed {len(arrays)} sprite arrays, {total} B -> {len(comp)} B ZX0")
    print(f"arena ${arena:04X}..${arena+total:04X}; uncontended freed ~{total-len(comp)} B")


if __name__ == "__main__":
    main()
